In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [49]:
#!pip install scipy

In [50]:
#!python.exe -m pip install --upgrade pip


In [51]:
#!pip install statsmodels

In [52]:
from statsmodels.stats.weightstats import ztest as ztest
import numpy as np
from scipy import stats
#enter IQ levels for 20 participants

data = [88,92,94,94,96,97,97,97,99,99,
        105,109,109,109,110,112,112,113,114,115]
print(np.mean(data))

ztest_stats, p_value = ztest(data,value=100)

103.05


In [53]:
print(ztest_stats)
print(p_value)
alpha = 0.05
if p_value<=alpha:
    print("Reject Ho")
else:
    print("Accept Ho")

1.5976240527147705
0.1101266701438426
Accept Ho


In [54]:
if ztest_stats > 1.96 and ztest_stats <= 1.96:
    print("Reject Ho")
else:
    print("Accept Ho")

Accept Ho


In [55]:
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]

In [56]:
import numpy as np
ages_mean = np.mean(ages)
ages_mean

np.float64(30.34375)

In [57]:
sample_size=10
age_sample=np.random.choice(ages,sample_size)

In [58]:
print(age_sample)

[32 55 16 14 25 18 43 24 18 24]


In [59]:
np.mean(age_sample)

np.float64(26.9)

In [60]:
from scipy.stats import ttest_1samp

In [61]:
s,p = ttest_1samp(age_sample,45)
if p<=0.05:
    print("Ho rejected")
else:
    print("Ho accepted")

Ho rejected


In [62]:
ttest_1samp(age_sample, 31)

TtestResult(statistic=np.float64(-0.9915164220161403), pvalue=np.float64(0.3473405929535486), df=np.int64(9))

In [63]:
ttest_1samp(age_sample, 28)

TtestResult(statistic=np.float64(-0.2660166010287208), pvalue=np.float64(0.7962201620494463), df=np.int64(9))

In [64]:
ttest_1samp(age_sample, 18)

TtestResult(statistic=np.float64(2.1523161355960108), pvalue=np.float64(0.059810808968623036), df=np.int64(9))

In [65]:
#consider another Example
#age of the college studnets(population)
#1 class student mean of all the ages

In [66]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math
np.random.seed(10)# generates random data
#creating the dumy data
school_ages = stats.poisson.rvs(mu=30,size = 2000)# 30 is the mean age
classA_ages = stats.poisson.rvs(mu=35,size=80) #35 is the mean age

In [67]:
print(school_ages)

[35 32 30 ... 24 19 30]


In [68]:
print(classA_ages)

[33 27 26 31 35 37 37 36 29 50 44 32 39 33 32 34 49 35 26 34 33 39 32 36
 40 39 33 29 42 29 33 38 29 32 31 29 26 31 40 26 41 28 25 37 25 29 46 36
 46 26 34 55 37 29 36 32 44 27 38 33 34 36 30 32 37 32 31 44 41 32 26 29
 48 35 32 35 30 38 27 39]


In [69]:
classA_ages.mean() #built in function for mean. another method

np.float64(34.475)

In [70]:
tstatistics, p_value = ttest_1samp(classA_ages,popmean = school_ages.mean())

In [71]:
if p_value <= 0.05:
    print("Reject H0")
else:
    print("Accept H0")

Reject H0


In [72]:
school_ages.mean()

np.float64(29.77)

In [73]:
#t test for independent samples

A z-test is used to test a Null Hypothesis if the population variance is known, or if the sample size is larger than 30, for an unknown population variance. A t-test is used when the sample size is less than 30 and the population variance is unknown

In [74]:
np.random.seed(10)
ClassB_ages = stats.poisson.rvs(mu=32,size = 60)
ClassB_ages.mean()

np.float64(31.05)

In [75]:
_p,p_value = stats.ttest_ind(a = classA_ages,b=ClassB_ages,equal_var=False)

In [76]:
if p_value < 0.5: #alpha value is 0.05 or 5%
    print("We are rejecting null hypothesis: classes are same, dependent")
else:
    print("We are accepting null hypothesis: classes are different, independent")

We are rejecting null hypothesis: classes are same, dependent


In [77]:
#paired t test with python

The paired sample t-test, sometimes called the dependent sample t-test, is a statistical procedure used to determine whether the mean difference between two sets of observations is zero. In a paired sample t-test, each subject or entity is measured twice, resulting in pairs of observations.

In [78]:
weight1=[25,30,28,35,28,34,26,29,30,26,28,32,31,30,45]
weight2=weight1+stats.norm.rvs(scale=5,loc=-1.25,size=15) #loc = location parameter

In [79]:
print(weight1)
print(weight2)

[25, 30, 28, 35, 28, 34, 26, 29, 30, 26, 28, 32, 31, 30, 45]
[30.66616115 30.48116558 31.86258054 34.58405134 35.03358312 36.08944804
 23.60026678 22.10224403 25.55018698 26.31915261 20.6208201  29.64103432
 36.44963155 28.89654855 53.67692873]


In [80]:
weight_df=pd.DataFrame({"weight_10":np.array(weight1),
                          "weight_20":np.array(weight2),
                           "weight_change":np.array(weight2)-np.array(weight1)})

In [81]:
weight_df

,weight_10,weight_20,weight_change
0,25,30.666161,5.666161
1,30,30.481166,0.481166
2,28,31.862581,3.862581
3,35,34.584051,-0.415949
4,28,35.033583,7.033583
5,34,36.089448,2.089448
6,26,23.600267,-2.399733
7,29,22.102244,-6.897756
8,30,25.550187,-4.449813
9,26,26.319153,0.319153


In [82]:
_,p_value=stats.ttest_rel(a=weight1,b=weight2)

In [83]:
print(p_value)

0.6581967217593208


In [84]:
if p_value < 0.05:
    print("We are rejecting null hypothesis")
else:
    print("We are accepting null hypothesis")


We are accepting null hypothesis


In [85]:
#chi-Square test


The chi-square test, also known as the Pearson chi-square test or χ2 test, is a statistical test used to determine whether there is a significant association between two categorical variables. It is a non-parametric test, which means it doesn't require normality or equal variances, making it a popular choice for many types of data.

In [86]:
import scipy.stats as stats
import pandas as pd
import numpy as np
dataset= sns.load_dataset('tips')

In [87]:
dataset.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [88]:
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [89]:
print(dataset_table.values)

[[60 97]
 [33 54]]


In [90]:
#Observed values
Observed_Values=dataset_table.values
print("Observed Values:- \n",Observed_Values)

Observed Values:- 
 [[60 97]
 [33 54]]


In [91]:
chi2_stats,p_value,dof,expected_values=stats.chi2_contingency(dataset_table)

In [92]:
alpha=0.05
critical_value = stats.chi2.ppf(q=1-alpha,df=dof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [93]:
p_value

np.float64(1.0)

In [94]:
#_________________________________________Chi Square Formula_____________________________________________
# ______________________________________TWO METHODS______________________________________________________________________________
#METHOD-1
#-------------------------------------------------------------------------------------------------------
# if chi2_stats>=critical_value:
#    print("Reject H0, There is a relationship between 2 categorical variance")
#else:
#    print("Accept H0, There is no relationship betweeen 2 categorical varince")
#________________________________________________OR_____________________________________________

#METHOD-2
#________________________________________________________________________________________________

if p_value<=alpha: # this is better that previous because no need to calculate critical value here
    print("Reject H0, There is a relationship between 2 categorical variance")
else:
    print("Reject H0, There is NO relationship between 2 categorical variance")

Reject H0, There is NO relationship between 2 categorical variance
